name: Bug report
description: Report build and runtime bugs
labels: ["Type: Bug"]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Answers checklist.
      description: Before submitting a new issue, please follow the checklist and try to find the answer.
      options:
              - Linux
              - MacOS
              - RaspberryPi OS
              - Windows 7
              - Windows 10
              - Windows 11
              - Others
    validations:
      required: true

  - type: input
    attributes:
      label: Commit SHA
      placeholder: e.g 3a042b37da28d0ba1e5593eb1068ca5645d77b56 or version bundled by esp-idf or pico-sdk
    validations:
      required: true

  - type: input
    id: idf_version
    attributes:
      label: Board
      placeholder: e.g Adafruit Feather nRF52840 Express
    validations:
      required: true
  - type: input
    id: devkit
    attributes:
      label: Development Kit.
      description: Which Development Kit does this issue occur on?
      placeholder: ex. ESP32-Wrover-Kit v2 | Custom Board
    validations:
      required: true
  - type: input
    id: component_version
    attributes:
      label: Used Component version.
      description: Which Component version does this issue occur on? Check `dependencies.lock` file in your project root to find it.
      placeholder: ex. v1.2.0-rc0
    validations:
      required: true
  - type: textarea
    id: more-info
    attributes:
      label: More Information.
      description: Any other information from investigating this?
      placeholder: ex. I tried on Windows 10 PC and the issue couldn't be reproduced there.
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: I have checked existing issues, dicussion and documentation
      description: You agree to check all the resources above before opening a new issue.
      options:
        - label: I confirm I have checked existing issues, dicussion and documentation.
          required: true
